// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhcDGHPN0ayazMRdZYmrVLNigcza5BirY',
    appId: '1:618301097278:web:4ba4110cdd7725ca81586f',
    messagingSenderId: '618301097278',
    projectId: 'benefit-bits-33e89',
    authDomain: 'benefit-bits-33e89.firebaseapp.com',
    storageBucket: 'benefit-bits-33e89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU9eBXEXFYjvuw7Q8So9Tv-y9Uv0snJ2o',
    appId: '1:618301097278:android:2a3299cf2849553281586f',
    messagingSenderId: '618301097278',
    projectId: 'benefit-bits-33e89',
    storageBucket: 'benefit-bits-33e89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0plHV3XCHGFPZVaHzNFEK7HWkNT1naA',
    appId: '1:618301097278:ios:e22f6a7d4d9d41e981586f',
    messagingSenderId: '618301097278',
    projectId: 'benefit-bits-33e89',
    storageBucket: 'benefit-bits-33e89.appspot.com',
    iosBundleId: 'com.example.flutterprojNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa0plHV3XCHGFPZVaHzNFEK7HWkNT1naA',
    appId: '1:618301097278:ios:0bcb8a9218e4236981586f',
    messagingSenderId: '618301097278',
    projectId: 'benefit-bits-33e89',
    storageBucket: 'benefit-bits-33e89.appspot.com',
    iosBundleId: 'com.example.flutterprojNew.RunnerTests',
  );
}
